server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: none
management:
  endpoints:
    web:
      exposure:
        include: "*"
app:
  feign:
    url: https://randomuser.me/api/?inc=name,email,dob
  db:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    name: postgres
    username: postgres
    password: postgres
    container-datasource: true
    postgresql-version: postgres:11-alpine
  job-initial-delay: 30000
  job-delay: 10000
